config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :homes
    root "homes#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale.to_sym : nil
  end
end

app/controllers/homes_controller.rb
require 'httparty'

class HomesController < ApplicationController  
  include HTTParty

  def index
    @selected_city = nil
    if params[:city].present? || params[:date]
      @selected_city = params[:city]
      @selected_date = params[:date]
      month = Date.parse(@selected_date).strftime("%m")
      year = Date.parse(@selected_date).strftime("%Y")
      @prayer_time = get_prayer_time(city: @selected_city, month: month, year: year)
      if @prayer_time.present?
        @prayer_time = @prayer_time.map {|entry| {entry["tanggal"] => entry.except("tanggal")} }
      end
      @city_name = get_city_name
    else
      @selected_city = 'jakartapusat'
      @selected_date = Date.today.strftime("%Y-%m-%d")
      @prayer_time = get_prayer_time(city: 'jakartapusat').map {|entry| {entry["tanggal"] => entry.except("tanggal")} }
      @city_name = get_city_name
    end
    all_ayah_info = get_random_ayah
    @surah = all_ayah_info["surah"]
    @ayah = all_ayah_info["ayah"]
    @dua = get_random_dua
  end
  
  private
  
  def get_prayer_time(city: nil, month: nil, year: nil)
    unless city.present?
      city = 'jakartapusat'.freeze
    end
    unless month.present?
      month = Date.today.strftime("%m")
    end
    unless year.present?
      year = Date.today.strftime("%Y")
    end
    url = "https://cdn.statically.io/gh/lakuapik/jadwalsholatorg/master/adzan/#{city}/#{year}/#{month}.json"
    response = HTTParty.get(url).parsed_response
    if response.is_a?(String)
      nil
    else
      response
    end
  end

  def get_city_name
    url = "https://raw.githubusercontent.com/lakuapik/jadwalsholatorg/master/kota.json"
    response = JSON.parse(HTTParty.get(url).parsed_response)
  end

  def get_random_ayah
    url_list_surah_ayah = "http://api.alquran.cloud/v1/surah"
    surah = HTTParty.get(url_list_surah_ayah).parsed_response["data"][rand(0..113)]
    url_random_ayah = "https://quran-endpoint.vercel.app/quran/#{surah["number"]}/#{rand(1..surah["numberOfAyahs"])}"
    response = HTTParty.get(url_random_ayah).parsed_response["data"]
  end

  def get_random_dua
    url = "https://doa-doa-api-ahmadramadhan.fly.dev/api/doa/v1/random"
    response = HTTParty.get(url).parsed_response.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div class="d-flex flex-column min-vh-100">
  <%= render "layouts/navbar" %>
  <div class="container mb-5">
    <div class="d-flex justify-content-end mt-3">
      <form class="d-flex" role="search" action="<%= homes_path %>">
        <select name="city" id="city" class="form-select form-select-sm me-2 my-auto" aria-label=".form-select-sm example" required>
          <% if @selected_city.present? %>
            <option value="<%= @selected_city %>" selected><%= @selected_city.titleize %></option>
          <% else %>
            <option selected disabled hidden><%= I18n.t('home.please_choose_city') %></option>
          <% end %>
          <% @city_name.each do |city| %>
            <option value="<%= city %>"><%= city.titleize %></option>
          <% end %>
        </select>
        <input type="date" class="form-control form-control-sm me-2 my-auto" id="date" name ="date" value="<%= @selected_date %>" required>
        <button class="btn btn-outline-success" type="submit"><%= I18n.t('miscellaneous.submit') %></button>
      </form>
    </div>
    <% unless @prayer_time.present? %>
      <div class="div text-center mt-4">
        <h4><%= I18n.t('home.no_data') %></h4>
      </div>
    <% else %>
      <div class="div text-center mt-4">
        <h4><%= I18n.t('home.header_1', attribute: @selected_city.titleize) %></h4>
        <h4><%= I18n.t('home.header_2', attribute: l(Date.parse(@selected_date), format: '%d %B %Y')) %></h4>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <% selected_date_prayer_time = @prayer_time.reject { |list| list.keys.first != @selected_date }.first.values.first %>
        <div class="w-75 table-responsive-sm">
          <table class="table table-borderless text-center">
            <thead>
              <tr>
                <th><%= I18n.t('home.imsyak') %></th>
                <th><%= I18n.t('home.shubuh') %></th>
                <th><%= I18n.t('home.sunrise') %></th>
                <th><%= I18n.t('home.dhuha') %></th>
                <th><%= I18n.t('home.dzuhur') %></th>
                <th><%= I18n.t('home.ashr') %></th>
                <th><%= I18n.t('home.maghrib') %></th>
                <th><%= I18n.t('home.isya') %></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= selected_date_prayer_time["imsyak"] %></td>
                <td><%= selected_date_prayer_time["shubuh"] %></td>
                <td><%= selected_date_prayer_time["terbit"] %></td>
                <td><%= selected_date_prayer_time["dhuha"] %></td>
                <td><%= selected_date_prayer_time["dzuhur"] %></td>
                <td><%= selected_date_prayer_time["ashr"] %></td>
                <td><%= selected_date_prayer_time["magrib"] %></td>
                <td><%= selected_date_prayer_time["isya"] %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="text-center mt-4">
        <h4><%= I18n.t('home.header_3', attribute: l(Date.parse(@selected_date), format: '%B %Y')) %></h4>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <div class="table-responsive">
          <table class="table table-striped table-hover text-center">
            <thead>
              <tr>
                <th><%= I18n.t('home.date') %></th>
                <th><%= I18n.t('home.imsyak') %></th>
                <th><%= I18n.t('home.shubuh') %></th>
                <th><%= I18n.t('home.sunrise') %></th>
                <th><%= I18n.t('home.dhuha') %></th>
                <th><%= I18n.t('home.dzuhur') %></th>
                <th><%= I18n.t('home.ashr') %></th>
                <th><%= I18n.t('home.maghrib') %></th>
                <th><%= I18n.t('home.isya') %></th>
              </tr>
            </thead>
            <tbody>
              <% @prayer_time.each do |pray| %>
                <tr>
                  <td><%= l(Date.parse(pray.keys.first), format: '%d %b') %></td>
                  <td><%= pray.values.first["imsyak"] %></td>
                  <td><%= pray.values.first["shubuh"] %></td>
                  <td><%= pray.values.first["terbit"] %></td>
                  <td><%= pray.values.first["dhuha"] %></td>
                  <td><%= pray.values.first["dzuhur"] %></td>
                  <td><%= pray.values.first["ashr"] %></td>
                  <td><%= pray.values.first["magrib"] %></td>
                  <td><%= pray.values.first["isya"] %></td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
              <tr>
                <th><%= I18n.t('home.date') %></th>
                <th><%= I18n.t('home.imsyak') %></th>
                <th><%= I18n.t('home.shubuh') %></th>
                <th><%= I18n.t('home.sunrise') %></th>
                <th><%= I18n.t('home.dhuha') %></th>
                <th><%= I18n.t('home.dzuhur') %></th>
                <th><%= I18n.t('home.ashr') %></th>
                <th><%= I18n.t('home.maghrib') %></th>
                <th><%= I18n.t('home.isya') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    <% end %>
    <hr>
    <div class="text-center mt-4">
      <h4><%= I18n.t('home.random_ayah') %></h4>
      <div>
        <h6><%= "#{@surah[params[:locale]]["long"]} (#{@surah["translation"][params[:locale]]}) #{I18n.t('home.ayah')} #{@ayah["number"]["insurah"]}" %></h6>
        <div class="box text-center">
          <div class="arab text-center">
            <%= @ayah["text"]["ar"] %>
          </div>
          <p class="text-muted mt-2"><%= "\"#{@ayah["text"]["read"]}\"" %></p>
          <p><%= "\"#{@ayah["translation"][params[:locale]]}\"" %></p>
        </div>
        <div>
          <audio src="<%= audio_path @ayah["audio"]["url"] %>" type="audio/mpeg" controls>
            <%= I18n.t('home.errors.audio_element') %>
          </audio>
        </div>
      </div>
    </div>
    <hr>
    <div class="text-center mt-4">
      <h4><%= I18n.t('home.random_dua') %></h4>
      <p class="text-muted"><%= I18n.t('home.errors.not_available_en') %></p>
      <div>
        <h6><%= "#{@dua["doa"]}" %></h6>
        <div class="box text-center">
          <div class="arab text-center">
            <%= @dua["ayat"] %>
          </div>
          <p class="text-muted mt-2"><%= @dua["latin"].capitalize %></p>
          <p><%= @dua["artinya"] %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="mb-5">
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-auto border-top fixed-bottom bg-light">
  <div class="container d-flex justify-content-between align-items-center py-3">
    <div class="col-md-4 d-flex align-items-center w-50">
      <div class="row">
        <div class="col-sm my-auto">
          <span class="text-muted text-sm"><%= I18n.t('footer.author') %></span>
        </div>
      </div>
    </div>
    <div class="d-flex col-md-4 justify-content-end">
      <ul class="nav list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="#"><%= image_tag("twitter.svg", size: "24") %></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><%= image_tag("instagram.svg", size: "24") %></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><%= image_tag("facebook.svg", size: "24") %></a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container">
    <a class="navbar-brand" href="<%= homes_path %>"><%= I18n.t('site_title') %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"><%= I18n.t('navbar.home') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#"><%= I18n.t('navbar.contact_me') %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= I18n.t('navbar.language') %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= root_path(locale: :en) %>"><%= I18n.t('navbar.en') %></a></li>
            <li><a class="dropdown-item" href="<%= root_path(locale: :id) %>"><%= I18n.t('navbar.id') %></a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMoreMoslem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>